// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TurnipTallyApi.Database;

namespace TurnipTallyApi.Migrations
{
    [DbContext(typeof(TurnipContext))]
    [Migration("20200428230536_UserTimezone")]
    partial class UserTimezone
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("TurnipTallyApi.Database.Entities.Board", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditKey")
                        .HasColumnType("TEXT");

                    b.Property<long>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Private")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrlName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("TurnipTallyApi.Database.Entities.BoardUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BoardId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long>("RegisteredUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("RegisteredUserId");

                    b.ToTable("BoardUsers");
                });

            modelBuilder.Entity("TurnipTallyApi.Database.Entities.Record", b =>
                {
                    b.Property<long>("BoardUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("WeekDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Day")
                        .HasColumnType("TEXT");

                    b.Property<string>("Period")
                        .HasColumnType("TEXT");

                    b.Property<int>("SellPrice")
                        .HasColumnType("INTEGER");

                    b.HasKey("BoardUserId", "WeekDate", "Day", "Period");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("TurnipTallyApi.Database.Entities.RegisteredUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<string>("TimezoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RegisteredUsers");
                });

            modelBuilder.Entity("TurnipTallyApi.Database.Entities.Week", b =>
                {
                    b.Property<long>("BoardUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("WeekDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("BuyPrice")
                        .HasColumnType("INTEGER");

                    b.HasKey("BoardUserId", "WeekDate");

                    b.ToTable("Weeks");
                });

            modelBuilder.Entity("TurnipTallyApi.Database.Entities.Board", b =>
                {
                    b.HasOne("TurnipTallyApi.Database.Entities.RegisteredUser", "Owner")
                        .WithMany("OwnedBoards")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TurnipTallyApi.Database.Entities.BoardUser", b =>
                {
                    b.HasOne("TurnipTallyApi.Database.Entities.Board", "Board")
                        .WithMany("Users")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TurnipTallyApi.Database.Entities.RegisteredUser", "RegisteredUser")
                        .WithMany("BoardUsers")
                        .HasForeignKey("RegisteredUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TurnipTallyApi.Database.Entities.Record", b =>
                {
                    b.HasOne("TurnipTallyApi.Database.Entities.Week", "Week")
                        .WithMany("Records")
                        .HasForeignKey("BoardUserId", "WeekDate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TurnipTallyApi.Database.Entities.Week", b =>
                {
                    b.HasOne("TurnipTallyApi.Database.Entities.BoardUser", "BoardUser")
                        .WithMany("Weeks")
                        .HasForeignKey("BoardUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
